### ISSUE TITLE
Don't use MmMapIoSpaceEx or NdisWriteErrorLogEntry in RtGetResources

### ISSUE THREAD

**Issue by jtippet** [Microsoft/NetAdapter-Cx-Driver-Samples#6]
It should be WdfDeviceMapIoSpace.

**Comment by AndrewGaspar** [comment]
WdfDeviceMapIoSpace is only available in user mode.

**Comment by AndrewGaspar** [comment]
Additionally, we don't have a replacement for NdisWriteErrorLogEntry, though I don't know how valuable the log statements are.
